language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - rey.webhouse.net
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_deploy:
- openssl aes-256-cbc -K $encrypted_97550da300e1_key -iv $encrypted_97550da300e1_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/service-deploy.sh dev $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: dev
- provider: script
  script: bash scripts/service-deploy.sh master $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    recipients:
    - cb@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: y0CEffrTBtQZWoNge3EEycYg0hCOiWWaqyiQ7Ob7HE3+RTE0kGGMiUMDnJ3cm0BW3aynTO42UW6VqoGgIvZlmsKNk98Z43YKz56gT06wn6Y0M7WdacPrgXYtB7PdLE5uBFiPiMV9ifdeqx3YGupSetyo3u7bKgIM0AkRcyjy/Y3TGCy16uLm+Jc46lD8S5/q9b9YeeVO7PXZ8DGUrRAYXjtY1hrNQxEcwm5+ZW0QzyFznJvHkBNEqlRkm23s/19/T7T/fUrdvtniwBmV/PUh2cXOViYzO7qaQ92dBpvslpC4mHUJNV2uUKQFfGaDVqCzAsf7p78Fu3eAK/euk77JVnqh4q8Xpf+FZnceIUPSLoQOseXpfgcLetKmHJZKKBlUQ8o+VGG4Qfye6h3GJdD7VYbQV+YU5+7ExQBRMS+CbClENE2y7KzTsJO7/3JyLXoeTxbAOJ+J3R64OSjjap8bYW/ayynZQs7qGOLCj83AuexQ5f6nsmnzo9lvrFc7ytsnPJNS6klotCLHsqQgBPEgN8qHs9Hv6GV4xtHcIadIRmjx9pmJgZ3Uv/VUD6CHlWwqxGQJi2BrFeBszJe1FmZ88ZYuBS+cBnsbqF9ExzfWFwq94cXWFEP2BUyxLhs4Zu4jr856fMxquyvuomaea9Fcbwmy6WOVq9a35B34DL+d2BY=
